name: takhlees_v
description: A new Flutter application.


# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  geolocator: ^6.1.8
  geocoder: ^0.2.1
  fluttertoast: ^3.1.0
  get: ^3.15.0
  logger: ^0.9.4
  device_info: ^0.4.2+9
  keyboard_actions: ^3.3.1
  flutter_svg: ^0.19.0
  image_picker: ^0.6.7+11
  http: ^0.12.2
  dio: ^3.0.10
  shared_preferences: ^0.5.11
  map: ^0.2.0+1
  cached_network_image: ^2.3.3
  url_launcher: ^5.7.10
  flutter_slidable: ^0.5.7
  google_maps_flutter: ^1.0.6
  image_cropper: ^1.3.1
  provider: ^4.3.2+3
  transparent_image: ^1.0.0
  onesignal_flutter: ^2.6.3
  timer_count_down: ^1.0.4+1
  intl: ^0.15.7
  future_progress_dialog: ^0.2.0
  flutter_staggered_animations: ^1.0.0
  clay_containers: ^0.3.2
  readmore: ^2.0.0
  flutter_rating_bar: ^4.0.0
  path_provider: any
  webview_flutter: ^2.0.2
#  firebase_auth: any
  firebase_core: ^0.5.0
  file_picker: ^2.1.7
  cloud_firestore: any
  share: ^2.0.4
#  pinch_zoom: ^1.0.0
#  easy_image_viewer: ^1.0.2
#  webview_flutter: ^2.0.12
  zoomable_image: ^1.3.1


#  firebase_messaging: ^7.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.8.0
  flutter_launcher_name: ^0.0.1


  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/takhlees_logo_dark_icon.png"

flutter_launcher_name:
  name: "Takhlees"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto-Black
      fonts:
        - asset: fonts/RobotoSlab-Black.ttf

    - family: Roboto-Bold
      fonts:
        - asset: fonts/RobotoSlab-Bold.ttf

    - family: Roboto-ExtraBold
      fonts:
        - asset: fonts/RobotoSlab-ExtraBold.ttf

    - family: Roboto-ExtraLight
      fonts:
        - asset: fonts/RobotoSlab-ExtraLight.ttf

    - family: Roboto-Light
      fonts:
        - asset: fonts/RobotoSlab-Light.ttf

    - family: Roboto-Medium
      fonts:
        - asset: fonts/RobotoSlab-Medium.ttf

    - family: Roboto-Regular
      fonts:
        - asset: fonts/RobotoSlab-Regular.ttf

    - family: Roboto-SemiBold
      fonts:
        - asset: fonts/RobotoSlab-SemiBold.ttf

    - family: Roboto-Thin
      fonts:
        - asset: fonts/RobotoSlab-Thin.ttf

    - family: FontsFree-Regular
      fonts:
        - asset: fonts/FontsFree-Net-SFProDisplay-Regular.ttf

    - family: FontsFree-Bold
      fonts:
        - asset: fonts/FontsFree-Net-SFProText-Bold.ttf




    - family: Fieldwork10-Regular
      fonts:
        - asset: fonts/Fieldwork10-GeoRegular.otf

    - family: Fieldwork12-ItalicRegular
      fonts:
        - asset: fonts/Fieldwork12-ItalicRegular.otf

    - family: Fieldwork16-Bold
      fonts:
        - asset: fonts/Fieldwork16-GeoBold.otf

    - family: Fieldwork18-ItalicBold
      fonts:
        - asset: fonts/Fieldwork18-ItalicBold.otf


    - family: Tajawal-Black
      fonts:
        - asset: fonts/Tajawal/Tajawal-Black.ttf

    - family: Tajawal-Bold
      fonts:
        - asset: fonts/Tajawal/Tajawal-Bold.ttf

    - family: Tajawal-ExtraBold
      fonts:
        - asset: fonts/Tajawal/Tajawal-ExtraBold.ttf

    - family: Tajawal-ExtraLight
      fonts:
        - asset: fonts/Tajawal/Tajawal-ExtraLight.ttf

    - family: Tajawal-Light
      fonts:
        - asset: fonts/Tajawal/Tajawal-Light.ttf

    - family: Tajawal-Medium
      fonts:
        - asset: fonts/Tajawal/Tajawal-Medium.ttf

    - family: Tajawal-Regular
      fonts:
        - asset: fonts/Tajawal/Tajawal-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
