const Map<String,String> ar = {
  'title':'الصفحة الرئيسية لعرض Flutter Demo',
  'textTitle':'لقد ضغطت على الزر عدة مرات:',
  'workingAvailability':'توافر العمل',
  'Select the day and time you’re working. You can always change it in settings.':'''حدد اليوم والوقت الذي تعمل فيهما.
يمكنك دائما تغييره في الإعدادات.''',
  'Sunday':'''الأحد''',
  'Monday':'''الأثنين''',
  'Tuesday':'''الثلاثاء''',
  'Wednesday':'''الأربعاء''',
  'Thursday':'''الخميس''',
  'Friday':'''الجمعة''',
  'Saturday':'''السبت''',
  'Next':'''التالي''',
  'Bahraini National':'''بحريني الجنسية''',
  'Expatriate':'''أجنبي''',
  'GCC National':'''مواطنين الخليج''',
  'Settings':'''إعدادات''',
  'GENERAL':'''جنرال لواء''',
  'Company Name':'''اسم الشركة''',
  'Name':'''اسم''',
  'Work Availability':'''توفر العمل''',
  'PRIVATE INFORMATION':'''معلومات خاصة''',
  'Email':'''البريد الإلكتروني''',
  'Mobile Phone':'''جوال''',
  'Notifications':'''إشعارات''',
  'Change Language':'''تغيير اللغة''',
  'Customer Care':'''رعاية العميل''',
  'About':'''حول''',
  'Terms and Conditions':'''الأحكام والشروط''',
  'Privacy Policy':'''سياسة الخصوصية''',

  'Company information':'''معلومات الشركة''',
  'Work schedule':'''جدول العمل''',
  'Manage services':'''إدارة الخدمات''',
  'Report':'''نقل''',
  'Team members':'''أعضاء الفريق''',
  'Saved Cards':'''البطاقات المحفوظة''',
  'language':'''لغة''',

  'Log out':'''تسجيل خروج''',
};

